### ISSUE TITLE
Repopulate setGlobalProperties across page reloads

### ISSUE THREAD

**Issue by wcjohnson11** [segment-integrations/analytics.js-integration-keen-io#3]
Currently, the Keen integration sets the setGlobalProperties with the user traits after an identify call is made, this ensures that the future .track() events will be sent with the user traits.
https://github.com/segment-integrations/analytics.js-integration-keen-io/blob/master/lib/index.js#L121

However, in the case of a page reload, setGlobalProperties becomes empty, sending no traits along with .track() calls unless .identify() is called again.

In order to fix this, the integration should be updated to check if there are traits stored in the analytics.user() object and populate setGlobalProperties with those, so that .identify() won't need to be called before .track() in order to send traits with the .track() call.

**Comment by BlackVegetable** [comment]
I might have a chance to work on this.  I am from Keen IO.  Do I need special permissions, or may I submit a PR at will?

**Comment by sperand-io** [comment]
Fire away! Thanks @BlackVegetable :)

**Comment by BlackVegetable** [comment]
Perhaps a dumb question: How do I get access to the `analytics.user()` object from within the `index.js` file?

**Comment by ndhoule** [comment]
Not at all a dumb question :+1: 

If you're trying to access it from within a `#track` (or `#identify`, etc.) call, you can access it by calling `this.analytics.user()`. Here's an example of it in the wild:

https://github.com/segment-integrations/analytics.js-integration-insidevault/blob/077fe134df901b5bf54c86afd5541f3d1f265620/lib/index.js#L31

Is that what you're looking for?

**Comment by BlackVegetable** [comment]
Yes indeed.  Thank you.  Javascript scoping is not yet one of my strong suits.

**Comment by BlackVegetable** [comment]
I'm getting an odd cleanup error from my test that is otherwise passing.  If you have a moment to take a look, I'll fix it up after and submit a PR.

**Comment by BlackVegetable** [comment]
Sorry, here is the link: https://gist.github.com/BlackVegetable/7e12a0c3d13bea4b0091

**Comment by ndhoule** [comment]
Ah yeah—that's because you're setting `analytics.user().traits`, which should be a function:

https://github.com/segmentio/analytics.js/blob/master/lib/entity.js#L135

Rather than doing an assignment, call `#traits` and pass in the traits you want to set on the user:

``` js
analytics.user().traits({ ... });
```

**Comment by BlackVegetable** [comment]
Aha, I was beginning to suspect that.  Thank you again.

**Comment by ndhoule** [comment]
Totally happy to help! Thanks for working on it, we really appreciate it.

**Comment by BlackVegetable** [comment]
Hey, I'm not sure if the PR notified you of its existence.  If not, this comment will.  (If you were already aware of it but haven't had time to look into it, I understand as well.)

**Comment by BlackVegetable** [comment]
I'm suddenly unable to get tests passing (even without my change) as I get the message: `Error loading resource http://localhost:49572/saucelabs.js (203)...`

Did something change on your end, or did I manage to goof up in a way that you know how to fix?

**Comment by ndhoule** [comment]
You can safely ignore that error. If your test suite isn't running it's likely because you have a syntax error somewhere; `make test-browser` will give you way better debugging output, so give that a shot and let me know what happens.

**Comment by BlackVegetable** [comment]
Ugh, `make test-browser` hangs without running the tests. That said, I'll double-check for syntax errors.

**Comment by BlackVegetable** [comment]
Nope, even my unchanged code will no longer test things.  I can't continue development on this unless I know why I'm getting `Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL http://localhost:50077/test/. Domains, protocols and ports must match.`.

**Comment by ndhoule** [comment]
Your branch isn't up to date with master. Try rebasing from upstream and let me know if the problem persists.

**Comment by BlackVegetable** [comment]
I've rebased it.  The change moving the code from `track()` to `initialize()` seems to be having trouble because `client.globalProperties` is `undefined` instead of being a function I can use at that point in time.  Thoughts?

**Comment by ndhoule** [comment]
Not positive without seeing your code, but I suspect you need to move your code into the `this.load` callback so it's executed after the Keen library has loaded. `#initialize` runs the Keen library stub, and `#load` then loads the full Keen library. I suspect `client.globalProperties` is set only when the full library loads. (If you want to push your code I can have a look and give more informed advice, too.)

**Comment by BlackVegetable** [comment]
Will do; thank you.

**Comment by BlackVegetable** [comment]
I've updated it with the test broken.  I think you are correct about the `load` call (why would I doubt you?)  I'm not familiar enough with how the `.load()` call works to shove the necessary arguments/context/function inside of it.  Can you give me an example?

`this.load(argumentA, argumentF);`

argumentA is the context needed by argumentF?  argumentF is the function to callback?

**Comment by ndhoule** [comment]
Sure; the signature for `this.load` can be found here: https://github.com/segmentio/analytics.js-integration/blob/master/lib/protos.js#L243

So [in Keen's case](https://github.com/BlackVegetable/analytics.js-integration-keen-io/commit/3b90410a21ed7077a8667d92c4d167b0f0914ce8#diff-6d186b954a58d5bb740f73d84fe39073R57), it's taking a bunch of locals used to populate the template string (the first arg), and `this.ready` as a callback. So you'd modify it something like this:

``` js
var self = this;
this.load({ lib: lib }, function() {
  // Your post-load code goes here
  self.ready();
});
```

**Comment by BlackVegetable** [comment]
Ah, I forgot how this flavor of Javascript bled variable scope like that.  (I come from a GJS background when it comes to Javascript.)  Thank you!

**Comment by BlackVegetable** [comment]
I'm still running into problems getting `keen.client` to even have a `client.globalProperties` (or a `client` at all.)  My latest attempt was pushed -f.

**Comment by ndhoule** [comment]
Does the Keen library load parts of itself asynchronously?

**Comment by BlackVegetable** [comment]
I'll ask.  This isn't my domain typically -- I was just trying to help out a particular customer.

**Comment by ndhoule** [comment]
My guess based on what you're describing is that it probably does—in that case, if the Keen library has some sort of publicly exposed `loaded` event, you could set an event listener on that.

That's the ideal case; the non-ideal case is that Keen doesn't expose something like that, in which case you can fall back on polling for library readiness:

``` js
// component.json dependencies section
"segmentio/when": "1.0.0"

// lib/index.js
var when = require('when');

// ...
// inside the `load` callback:

when(this.loaded, function() {
  // logic in here
});
```

This should work, but I'm not familiar with the innards of the Keen library—you might need to modify `this.loaded` depending on whether or not the Keen loads multiple independent parts of its library asynchronously. (That's why a `ready` event would be ideal.)

**Comment by BlackVegetable** [comment]
Apparently there _is_ a `Keen.ready` callback. Would that replace `this.load`?

**Comment by ndhoule** [comment]
@BlackVegetable No; calling `this.load` is what triggers loading of the full Keen script. Instead, you'll want to set up a listener on `Keen.ready` inside of the `this.load` callback, and only do work _after_ Keen is ready so you don't try to access `client.globalProperties` before it exists.

**Comment by hankim813** [comment]
Closing this issue for same reason as this PR being closed. https://github.com/segment-integrations/analytics.js-integration-keen-io/pull/4
